Repository wikimedia/service-runner, pull requests merged in 2019-06, with the labels that each got.

#216 Replace invalid IPs in README.md
  README.md
Labels: hygene

#217 Do not try to set the stack trace of undefined objects; rel v2.7.1
  lib/base_service.js
  package.json
Labels: bug, release

#219 Update dependencies; release v2.7.2
  package.json
Labels: release
