Repository wikimedia/service-runner, pull requests merged in 2019-05, with the labels that each got.

#209 Ensure unhandled errors contain the stack trace; rel v2.6.18
  lib/logger.js
  package.json
Labels: enhancement, release

#213 Don't override error stack if it is provided and rely on error code.
  lib/base_service.js
  lib/logger.js
Labels: bug, enhancement

#210 SIG* and event handler changes
  lib/base_service.js
  lib/heapwatch.js
  lib/logger.js
  lib/master.js
  lib/worker.js
  package.json
  test/features/tests.js
Labels: enhancement
